# Generated by Django 3.1.2 on 2020-10-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0002_carer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carer',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
